plugins {
    id('groovy')
    id('org.ajoberstar.git-publish')
}

repositories {
    mavenLocal()
    // Spring AI
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation "org.apache.groovy:groovy:$groovy"
    implementation project(":underdog-dataframe")
    implementation project(":underdog-graphs")
    implementation project(":underdog-ml")
    implementation project(":underdog-plots")
    implementation project(":underdog-ta")
    implementation project(":underdog-spectacle")
    implementation project(":underdog-sd-client")
    implementation 'ch.qos.logback:logback-classic:1.5.16'

    // EXAMPLES DEPENDENCIES
    // spring AI (SpringAISpec)
    implementation platform("org.springframework.ai:spring-ai-bom:1.1.1")
    implementation 'org.springframework.ai:spring-ai-client-chat'
    implementation 'org.springframework.ai:spring-ai-openai'

    // Scrapping (webscrapping.WebScrappingSpec)
    implementation 'org.jsoup:jsoup:1.18.1'
    implementation 'io.github.ollama4j:ollama4j:1.0.91'

    // Testing
    testImplementation "org.spockframework:spock-core:$spock"
}

tasks.register("setAuthentication") {
    doLast {
        System.setProperty("org.ajoberstar.grgit.auth.username", findProperty('PUBLISH_GH_TOKEN').toString())
    }
}

gitPublish {
    branch  = 'gh-pages'
    repoUri = 'https://github.com/grooviter/underdog.git'
    repoDir = file("build/gitPublish")

    contents {
        from file("build/docs")
    }
}

gitPublishPush {
    dependsOn 'setAuthentication'
}

test {
    useJUnitPlatform()
}