plugins {
    id('groovy')
    id('org.ajoberstar.git-publish')
    id("application")
}

repositories {
    mavenLocal()
}

dependencies {
    implementation "org.apache.groovy:groovy:$groovy"
    implementation project(":underdog-dataframe")
    implementation project(":underdog-graphs")
    implementation project(":underdog-ml")
    implementation project(":underdog-plots")
    implementation project(":underdog-ta")
    implementation project(":underdog-spectacle")
    implementation 'ch.qos.logback:logback-classic:1.5.16'
    testImplementation "org.spockframework:spock-core:$spock"
}

tasks.register("setAuthentication") {
    doLast {
        System.setProperty("org.ajoberstar.grgit.auth.username", findProperty('PUBLISH_GH_TOKEN').toString())
    }
}

gitPublish {
    branch  = 'gh-pages'
    repoUri = 'https://github.com/grooviter/underdog.git'
    repoDir = file("build/gitPublish")

    contents {
        from file("build/docs")
    }
}

gitPublishPush {
    dependsOn 'setAuthentication'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'underdog.spectacle.SpectacleApplication'
}