package underdog.guide.spectacle

import spock.lang.Specification
import underdog.DataFrame
import underdog.Underdog
import underdog.spectacle.Spectacle

import java.time.LocalDate
import java.time.LocalDateTime

class ComponentsSpec extends Specification {
    private static DataFrame loadDataFrame() {
        return Underdog.df()
            .read_csv(ComponentsSpec.class.classLoader.getResource("data/baseball.csv").file)
            .head(5)
    }
    def "inputs"() {
        setup:
        def app = Spectacle.application {
            page('/experiment', theme: "dark") {
                // --8<-- [start:markdown]
                markdown """\
                  | # Spectacle's Components
                  |
                  | This is a showcase of all available components in Spectacle.
                  | More information at [Spectacle's docs](https://grooviter.github.io/spectacle)
                """
                // --8<-- [end:markdown]
                row {
                    col(className: 'col-4') {
                        text(
                            name: field.textWithIcon,
                            label: 'Username',
                            info: 'Text input with icon',
                            placeHolder: 'youremail@yourcompany.com',
                            icon: 'bi bi-person'
                        )
                    }
                    col(className: 'col-4') {
                        text(
                            name: field.textWithIcon,
                            label: 'Subdomain to scrape',
                            info: 'Text input with prefix and suffix',
                            placeHolder: 'subdomain',
                            prefix: "https://",
                            suffix: ".yourdomain.com"
                        )
                    }
                    col(className: 'col-4') {
                        // --8<-- [start:text]
                        text(
                                name: field.text,                                    // string
                                label: 'Name',                                       // string
                                info: 'Name of the employee',                        // string
                                placeHolder: 'Insert name, example: John, Anna,...', // string
                        )
                        // --8<-- [end:text]
                    }
                }
                row {
                    col(className: 'col-4') {
                        // --8<-- [start:select]
                        select(
                            name: field.select,                       // string
                            label: 'Bike Brand',                      // string
                            info: 'Select your favourite bike brand', // string
                            className: "",                            // string
                        ) {
                            option(
                                0,        // Object
                                'Suzuki'  // Object
                            )
                            option(1, 'Honda')
                            option(2, 'Yamaha')
                            option(3, 'Kawasaki')
                        }
                        // --8<-- [end:select]
                    }
                    col(className: 'col-4') {
                        // --8<-- [start:textArea]
                        textArea(
                            name: field.textArea,                 // string
                            label: 'AI Answer',                   // string
                            info: "This will show the AI answer", // string
                            value: 'Hello, good morning',         // string
                            rows: 1,                              // number (5 by default)
                        )
                        // --8<-- [end:textArea]
                    }
                    col(className: 'col-4') {
                        // --8<-- [start:number]
                        number(
                                name: field.number,             // string (generated by default)
                                label: 'Temperature',           // string
                                info: 'Temperature in Celsius', // string
                                value: 3                        // number
                        )
                        // --8<-- [end:number]
                    }
                }
                row {
                    col(className: 'col-4') {
                        // --8<-- [start:range]
                        range(
                            name: field.range,              // string: name of the element (generated by default)
                            label: 'Percentage',            // string: label of the range
                            info: 'Choose the risk level',  // string: description of the range
                            className: "",                  // string: css classes attached to component
                            value: 50,                      // number: initial value
                            min: 0,                         // number: minimum value of the range
                            max: 100,                       // number: maximum value of the range
                            step: 25,                       // number: size of every step
                            symbol: '%',                    // string: shows symbol along with numbers
                            showMarkers: true,              // boolean: shows step ticks
                            showUpdatedValue: true          // boolean: shows the updated value
                        )
                        // --8<-- [end:range]
                    }
                }
                row {
                    col(className: 'col-4') {
                        // --8<-- [start:optionGroup]
                        optionGroup(label: 'Algorithm Type', info: 'Choose the algorithm matching the type of ML case') {
                            option("Classification", true)
                            option("Regression", false)
                        }
                        // --8<-- [end:optionGroup]
                    }
                    col(className: 'col-4') {
                        // --8<-- [start:checkboxGroup]
                        checkboxGroup(
                            name: field.features,                          // string: name of the element
                            label: 'Features',                             // string: label of the element
                            info: 'Choose the features to train the model' // string: description about the element
                        ){
                            option(
                                value: 'RS',                               // string: value of the checkbox
                                label: 'Runs Scored (RS)',                 // string: label of the checkbox
                                checked: false                             // boolean: whether should be checked or not
                            )
                            option(value: 'W', label: 'Wins (W)', checked: false)
                        }
                        // --8<-- [end:checkboxGroup]
                    }
                    col(className: 'col-4') {
                        // --8<-- [start:checkboxSwitchesGroup]
                        switchGroup(
                            name: field.checkboxSwitchesGroup,
                            label: 'Option Switches',
                            info: 'A checkboxGroup with the appearance of a switch group'
                        ) {
                            option(value: 'regularization', label: 'Regularization', checked: true)
                            option(value: 'normalization', label: 'Normalization', checked: false)
                        }
                        // --8<-- [end:checkboxSwitchesGroup]
                    }
                }
                row {
                    col(className: "col-2") {
                        // --8<-- [start:datePicker]
                        datePicker(
                            label: "Date",           // string: label of the element
                            info: "Date picker",     // string: information about the element
                            from: LocalDate.now(),   // java.time.LocalDate: lower bound limit
                            to: LocalDate.now()      // java.time.LocalDate: upper bound limit
                                .plusDays(20)
                        )
                        // --8<-- [end:datePicker]
                    }
                    col(className: "col-2") {
                        // --8<-- [start:timePicker]
                        timePicker(
                            label: "Time",             // string: label of the element
                            info: "Time picker",       // string: information about the element
                            from: LocalDateTime.now(), // java.time.LocalDateTime: lower bound
                            to: LocalDateTime.now()    // java.time.LocalDateTime: upper bound
                                .plusHours(2)
                        )
                        // --8<-- [end:timePicker]
                    }
                }
                row {
                    col(className: "col-2") {
                        // --8<-- [start:numberCard]
                        numberCard(
                            title: "Accuracy (test set)",
                            defaultValue: 89.3234,
                            symbol: "%"
                        )
                        // --8<-- [end:numberCard]
                    }
                }
                row {
                    col(className: "col-4"){
                        markdown """\
                        | ### Accordion
                        | 
                        | Accordion becomes handy for splitting many options
                        """
                        accordion {
                            section('Network') {
                                switchGroup {
                                    option(value: "wifi", label:"Wifi", checked: true)
                                    option(value: "bluetooth", label:"Bluetooth", checked: false)
                                    option(value: "nfc", label:"NFC", checked: false)
                                }
                            }
                            section('Link Social') {
                                switchGroup {
                                    option(value: "google", label:"Google", checked: true)
                                    option(value: "facebook", label:"Facebook", checked: false)
                                    option(value: "dropbox", label:"Dropbox", checked: false)
                                }
                            }
                            section('About') {
                                markdown "Some text there"
                            }
                        }
                    }
                }
                // --8<-- [start:dataframe]
                dataframe(
                    name: field.dataframe,              // string
                    label: 'Baseball Data',             // string
                    info: 'Shows Moneyball data csv',   // string
                    value: loadDataFrame()              // underdog.DataFrame
                )
                // --8<-- [end:dataframe]
                row {
                    col(className: "col-4") {
                        // --8<-- [start:card]
                        card {
                            cardHeader(
                                title: "AI question panel",
                                description: "Ask questions to the AI model"
                            )
                            cardBody {
                                textArea(label: "Question")
                            }
                            cardFooter {
                                button(text: "Send Question")
                            }
                        }
                        // --8<-- [end:card]
                    }
                    col(className: "col-4") {
                        card {
                            cardHeader(
                                title: "Chat bot demo",
                                description: "Ask questions to the AI model"
                            )
                            cardBody {
                                textArea(label: "Answer")
                            }
                            cardFooter {
                                text(label: "Question", placeHolder: "Insert your question here")
                            }
                        }
                    }
                    col(className: 'col-4') {
                        // --8<-- [start:chart]
                        chart(
                            name: field.chart,                      // string
                            label: 'Progression',                   // string
                            info: "Shows some metric progression",  // string
                            defaultValue: null,                     // underdog.plots.Options
                        ) {
                            // return underdog.plots.Options
                            return Underdog.plots().line(1..10, 40..50)
                        }
                        // --8<-- [end:chart]
                    }
                }
                // --8<-- [start:button]
                button(
                    name: field.button,        // string
                    text: 'Execute',           // string
                    className: '+btn-warning'  // string
                )
                // --8<-- [end:button]
                // --8<-- [start:resetLink]
                resetLink(
                    name: field.reset,         // string
                    text: 'Reset form',        // string
                    className: '+link-danger'   // string
                )
                // --8<-- [end:resetLink]
            }
        }
        expect:
        //app
        app.launch()
    }
}
