package underdog.guide.spectacle

import spock.lang.Specification
import underdog.DataFrame
import underdog.Underdog
import underdog.spectacle.Spectacle

class ComponentsSpec extends Specification {
    private static DataFrame loadDataFrame() {
        return Underdog.df()
            .read_csv(ComponentsSpec.class.classLoader.getResource("data/baseball.csv").file)
            .head(10)
    }
    def "inputs"() {
        setup:
        def app = Spectacle.application {
            page('/experiment') {
                // --8<-- [start:markdown]
                markdown """\
                  | # Spectacle's components
                  |
                  | This is a showcase of all available components in Spectacle
                  |
                  | - number()
                  | - text()
                  | - ...etc
                  |
                  | More information at [Spectacle's docs](https://grooviter.github.io/spectacle)
                """
                // --8<-- [end:markdown]
                // --8<-- [start:number]
                number(
                    name: field.number,             // string (generated by default)
                    label: 'Temperature',           // string
                    info: 'Temperature in Celsius', // string
                    value: 3                        // number
                )
                // --8<-- [end:number]
                // --8<-- [start:range]
                range(
                    name: field.range,              // string (generated by default)
                    label: 'Percentage',            // string
                    info: 'Choose the risk level',  // string
                    className: "",                  // string
                    value: 30                       // number
                )
                // --8<-- [end:range]
                // --8<-- [start:text]
                text(
                    name: field.text,                                    // string
                    label: 'Name',                                       // string
                    info: 'Name of the employee',                        // string
                    placeHolder: 'Insert name, example: John, Anna,...', // string
                )
                // --8<-- [end:text]
                // --8<-- [start:select]
                select(
                    name: field.select,                       // string
                    label: 'Bike Brand',                      // string
                    info: 'Select your favourite bike brand', // string
                    className: "",                            // string
                ){
                    option(
                        0,        // Object
                        'Suzuki'  // Object
                    )
                    option(1, 'Honda')
                    option(2, 'Yamaha')
                    option(3, 'Kawasaki')
                }
                // --8<-- [end:select]

                // --8<-- [start:optionGroup]
                optionGroup(label: 'Algorithm Type', info: 'Choose the algorithm matching the type of ML case') {
                    option("Classification", true)
                    option("Regression", false)
                }
                // --8<-- [end:optionGroup]

                row {
                    col(className: 'col-4') {
                        // --8<-- [start:chart]
                        chart(
                            name: field.chart,                      // string
                            label: 'Progression',                   // string
                            info: "Shows some metric progression",  // string
                            defaultValue: null,                     // underdog.plots.Options
                        ) {
                            // return underdog.plots.Options
                            return Underdog.plots().line(1..10, 40..50)
                        }
                        // --8<-- [end:chart]
                    }
                }

                // --8<-- [start:dataframe]
                dataframe(
                    name: field.dataframe,              // string
                    label: 'Baseball Data',             // string
                    info: 'Shows Moneyball data csv',   // string
                    value: loadDataFrame()              // underdog.DataFrame
                )
                // --8<-- [end:dataframe]

                row {
                    col(className: 'col-4') {
                        // --8<-- [start:textArea]
                        textArea(
                            name: field.textArea,             // string
                            label: 'Conversation',            // string
                            value: 'Hello, good morning',     // string
                            rows: 3,                          // number (5 by default)
                        )
                        // --8<-- [end:textArea]
                    }
                }

                // --8<-- [start:button]
                button(
                    name: field.button,        // string
                    text: 'Execute',           // string
                    className: '+btn-warning'  // string
                )
                // --8<-- [end:button]


                // --8<-- [start:resetLink]
                resetLink(
                    name: field.reset,         // string
                    text: 'Reset form',        // string
                    className: '+link-danger'   // string
                )
                // --8<-- [end:resetLink]
            }
        }
        expect:
        app.launch()
    }
}
