/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.grooviter.underdog

import spock.lang.Specification
import com.github.grooviter.underdog.Underdog as ud
import tech.tablesaw.columns.Column

class GettingStartedTest extends Specification {
    static CSV_FOOD = "src/test/resources/com/github/grooviter/underdog/tablesaw/food.csv"

    def "read a CSV file"() {
        when:
        def df = ud.read_csv(path: CSV_FOOD, nanValues: ["NaN"], sep: ";")

        then:
        df.size() == 3197

        and:
        df.columns.size() == 20
    }

    def "Indexing: df['column']"() {
        setup:
        def df = ud.read_csv(path: CSV_FOOD, nanValues: ["NaN"], sep: ";")

        when:
        def carbs = df["CARBS"]

        then:
        carbs.size() == 3197
    }

    def "Indexing: df['column'][0]"() {
        setup:
        def df = ud.read_csv(path: CSV_FOOD, nanValues: ["NaN"], sep: ";")

        when:
        def carbs = df["CARBS"][0]

        then:
        carbs == 0.0
    }

    def "Indexing: df['column'].iloc[0]"() {
        setup:
        def df = ud.read_csv(path: CSV_FOOD, nanValues: ["NaN"], sep: ";")

        when:
        def carbs = df["CARBS"].iloc[9]

        then:
        carbs == 4.2
    }

    def "Indexing: df.loc['column']"() {
        setup:
        def df = ud.read_csv(path: CSV_FOOD, nanValues: ["NaN"], sep: ";")

        when:
        def carbs = df.loc["CARBS"]

        then:
        carbs.size() == 3197
    }
}
