package underdog.guide.spectacle.components

import underdog.spectacle.dsl.Context
import underdog.spectacle.dsl.HtmlApplication
import underdog.spectacle.dsl.HtmlPage

import java.time.LocalDate
import java.time.LocalDateTime
import java.util.function.Function

import static underdog.guide.spectacle.components.Constants.CSS_3_COLS_RESPONSIVE

class FormPageProvider implements Function<HtmlApplication, HtmlPage>{
    @Override
    HtmlPage apply(HtmlApplication app) {
        return HtmlPage.create(
            path: "/components/form",
            title: "Form",
            preTitle: "Examples",
            application: app,
            icon: 'bi bi-list'
        ) {
            row {
                col {
                    markdown """\
                    | In this section you can find components used in forms for accepting input data
                    """
                }
            }
            form {
                row {
                    col(CSS_3_COLS_RESPONSIVE) {
                        text(
                            name: app.field.textWithIcon,
                            label: 'Username',
                            info: 'Text input with icon',
                            placeHolder: 'youremail@yourcompany.com',
                            icon: 'bi bi-person'
                        )
                        row {
                            // --8<-- [start:datePicker]
                            col("col-8") {
                                datePicker(
                                        label: "Date",           // string: label of the element
                                        info: "Date picker",     // string: information about the element
                                        from: LocalDate.now(),   // java.time.LocalDate: lower bound limit
                                        to: LocalDate.now()      // java.time.LocalDate: upper bound limit
                                                .plusDays(20)
                                )
                            }
                            // --8<-- [end:datePicker]
                            // --8<-- [start:timePicker]
                            col("col-4") {
                                timePicker(
                                        label: "Time",             // string: label of the element
                                        info: "Time picker",       // string: information about the element
                                        from: LocalDateTime.now(), // java.time.LocalDateTime: lower bound
                                        to: LocalDateTime.now()    // java.time.LocalDateTime: upper bound
                                                .plusHours(2)
                                )
                            }
                            // --8<-- [end:timePicker]
                        }
                        text(
                            name: app.field.text,                                    // string
                            label: 'Name',                                       // string
                            info: 'Name of the employee',                        // string
                            placeHolder: 'Insert name, example: John, Anna,...', // string
                        )
                        // --8<-- [start:textArea]
                        textArea(
                            name: app.field.textArea,             // string
                            label: 'Comments',                    // string
                            info: "Enter some comment",           // string
                            value: 'Hello, good morning',         // string
                            rows: 5,                              // number (5 by default)
                        )
                        // --8<-- [end:textArea]
                    }
                    col(CSS_3_COLS_RESPONSIVE) {
                        // --8<-- [start:number]
                        number(
                            name: app.field.number,             // string (generated by default)
                            label: 'Temperature',           // string
                            info: 'Temperature in Celsius', // string
                            value: 3                        // number
                        )
                        // --8<-- [end:number]
                        // --8<-- [start:select]
                        select(
                                name: app.field.select,                   // string
                                label: 'Bike Brand',                      // string
                                info: 'Select your favourite bike brand', // string
                                className: "",                            // string
                        ) {
                            option(
                                    0,        // Object
                                    'Suzuki'  // Object
                            )
                            option(1, 'Honda')
                            option(2, 'Yamaha')
                            option(3, 'Kawasaki')
                        }
                        // --8<-- [end:select]
                        // --8<-- [start:range]
                        range(
                            name: app.field.range,              // string: name of the element (generated by default)
                            label: 'Percentage',            // string: label of the range
                            info: 'Choose the risk level',  // string: description of the range
                            className: "",                  // string: css classes attached to component
                            value: 50,                      // number: initial value
                            min: 0,                         // number: minimum value of the range
                            max: 100,                       // number: maximum value of the range
                            step: 25,                       // number: size of every step
                            symbol: '%',                    // string: shows symbol along with numbers
                            showMarkers: true,              // boolean: shows step ticks
                            showUpdatedValue: true          // boolean: shows the updated value
                        )
                        // --8<-- [end:range]
                    }
                    col(CSS_3_COLS_RESPONSIVE) {
                        // --8<-- [start:optionGroup]
                        optionGroup(label: 'Algorithm Type', info: 'Choose the algorithm matching the type of ML case') {
                            option("Classification", true)
                            option("Regression", false)
                        }
                        // --8<-- [end:optionGroup]
                        // --8<-- [start:checkboxGroup]
                        checkboxGroup(
                            name: app.field.features,                          // string: name of the element
                            label: 'Features',                             // string: label of the element
                            info: 'Choose the features to train the model' // string: description about the element
                        ){
                            option(
                                value: 'RS',                               // string: value of the checkbox
                                label: 'Runs Scored (RS)',                 // string: label of the checkbox
                                checked: false                             // boolean: whether should be checked or not
                            )
                            option(value: 'W', label: 'Wins (W)', checked: false)
                        }
                        // --8<-- [end:checkboxGroup]
                        // --8<-- [start:checkboxSwitchesGroup]
                        switchGroup(
                            name: app.field.checkboxSwitchesGroup,
                            label: 'Option Switches',
                            info: 'A checkboxGroup with the appearance of a switch group'
                        ) {
                            option(value: 'regularization', label: 'Regularization', checked: true)
                            option(value: 'normalization', label: 'Normalization', checked: false)
                        }
                        // --8<-- [end:checkboxSwitchesGroup]
                    }
                }
                row {
                    col("${CSS_3_COLS_RESPONSIVE} d-flex justify-content-between") {
                        // --8<-- [start:button]
                        button(
                            name: app.field.button,    // string
                            text: 'Execute',           // string
                            className: '+btn-danger'   // string
                        )
                        // --8<-- [end:button]
                        // --8<-- [start:resetLink]
                        resetLink(
                            name: app.field.reset,     // string
                            text: 'Reset form',        // string
                            className: '+link-success' // string
                        )
                        // --8<-- [end:resetLink]
                    }
                }
                onSubmit([],[]) { Context ctx ->
                    println("Form sent!")
                }
            }
        }
    }
}
