name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    env:
      ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY_ID: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY_ID }}
      ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY }}
      ORG_GRADLE_PROJECT_PUBLISH_SIGN_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_SIGN_SECRET }}
      ORG_GRADLE_PROJECT_PUBLISH_REPO_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_REPO_USERNAME }}
      ORG_GRADLE_PROJECT_PUBLISH_REPO_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_REPO_PASSWORD }}
      ORG_GRADLE_PROJECT_PUBLISH_GH_TOKEN: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: installing poetry
        run: python -m pip install --upgrade pip && pip install poetry
      - name: building docs
        working-directory: docs/guide
        run: poetry install && poetry run mkdocs build
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: release
        run: |
          ./gradlew \
            --stacktrace \
            -x aggregateCodenarc \
            -x aggregateGroovydoc \
            build