package underdog.sd.cli

import spock.lang.Ignore
import spock.lang.TempDir
import underdog.sd.cli.common.SDAwareSpec
import underdog.sd.cli.sdcpp.CapabilitiesResult
import underdog.sd.cli.sdcpp.ImageGenerationOptions
import underdog.sd.cli.sdcpp.JobExecutionResult
import underdog.sd.cli.sdcpp.JobStatusResult
import underdog.sd.cli.sdcpp.VideoGenerationOptions
import underdog.sd.cli.sdcpp.domain.SampleParams

/**
 * Some tips learned from executing tests
 *
 * I2V
 *
 * Videos generated by a given image should mimic the image resolution as much as possible, otherwise
 * video generation will have to figure out many of the remaining pixels that were not in the image
 *
 * T2V
 *
 * Less than 832x480 is not worth it. Most of the models are trained with at least that resolution, less
 * than that struggles a lot
 *
 * More than 6 secs require more than 16 of VRAM unless you start using tsd
 *
 * @since 0.1.0
 */
class SDCPPClientSpec extends SDAwareSpec{
    def "/sdcpp/capabilities"() {
        when:
        CapabilitiesResult result = sdcpp.capabilities

        then:
        result

        and:
        result.model.name
        result.model.path
        result.model.stem

        and:
        result.schedulers.size() > 0
        result.samplers.size() > 0
    }

    def '/sdcpp/job/$id'() {
        when:
        JobExecutionResult executionResult = sdcpp.imgGen(ImageGenerationOptions.builder()
            .prompt("A dog")
            .cfgScale(1)
            .denoisingStrength(0.7)
            .samplerName("euler")
            .seed(200_002)
            .width(256)
            .height(256)
            .steps(4)
            .build())

        and:
        JobStatusResult statusResult = sdcpp.getJob(executionResult.id)

        then:
        statusResult.created
        statusResult.started
        statusResult.id == executionResult.id
        statusResult.status == 'generating'
    }

    @Ignore
    def '/sdcpp/job/$id/cancel'() {
        expect:
        false
    }

    def '/sdcpp/v1/img_gen'() {
        when:
        JobExecutionResult executionResult = sdcpp.imgGen(ImageGenerationOptions.builder()
            .prompt("A dog")
            .cfgScale(1)
            .denoisingStrength(0.7)
            .samplerName("euler")
            .seed(200_002)
            .width(256)
            .height(256)
            .steps(4)
            .build())

        and:
        JobStatusResult statusResult = awaitUntilJobStatusResult(executionResult.id)

        then:
        statusResult.id == executionResult.id
        statusResult.result.images.size() > 0
        statusResult.completed
    }

    def '/sdcpp/v1/vid_gen (i2v)'(@TempDir File videoDir) {
        setup:
        String loRA = """\
        | <lora:wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise:${loraStrenght}/>
        | <lora:wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise:${loraStrenght}/>
        """.stripIndent().stripMargin().replaceAll('\n', '')

        String prompt = """\
        | ${includeLoRA ? loRA : ''}
        | Reference image determines the character identity. The person is smiling and he winks.
        """.stripIndent().stripMargin()

        String negativePrompt = """\
        | cartoon, anime, CGI, rendered graphics, game engine, low resolution, blurry, distorted body, extra limbs, 
        | duplicate person, floating, unrealistic physics, warped aircraft interior, bad perspective, flickering, 
        | jitter, motion artifacts, overexposed, underexposed, low detail, unrealistic sky, deformed hands, 
        | deformed face, camera clipping through objects, text, watermark, logo, frame corruption
        """.stripMargin().stripIndent()

        when:
        String filename = """\
        | cfg-${cfgScale}-
        | st-${strength}-
        | flw-${flowShift}-
        | mt-${method}-
        | steps-${sampleSteps}-
        | sec-${seconds}-
        | Q8${includeLoRA ? "-Lora-${loraStrenght}" : ''}.webm
        """.stripMargin().stripIndent().replaceAll('\n', '')

        File video = new File(videoDir, filename)

        and:
        JobExecutionResult executionResult = sdcpp.vidGen(VideoGenerationOptions.builder()
            .prompt(prompt)
            .negativePrompt(negativePrompt)
            .initImage(arnoldSchwarzeneggerBase64Image)
            .cfgScale(cfgScale)
            .strength(strength)
            .sampleParams(SampleParams.builder()
                .flowShift(flowShift)
                .sampleMethod(method)
                .sampleSteps(sampleSteps)
                .build())
            .videoFrames(seconds * 24)
            .width(500)
            .height(633)
            .fps(24)
            .build())

        and:
        JobStatusResult statusResult = awaitUntilJobStatusResult(executionResult.id)

        and:
        video << statusResult.result.b64Json.decodeBase64()

        then:
        statusResult.id == executionResult.id
        statusResult.completed

        and:
        video.exists()

        where:
        strength | cfgScale | flowShift | method      | sampleSteps | includeLoRA | loraStrenght |seconds
        0.28     | 1        | 5.5       | 'dpm++2mv2' | 4           | true        | 1.0          | 2
        0.22     | 1        | 5.0       | 'dpm++2mv2' | 6           | true        | 1.0          | 4
        0.22     | 1        | 5.0       | 'dpm++2mv2' | 6           | true        | 0.7          | 4
        0.22     | 1        | 5.0       | 'dpm++2mv2' | 6           | true        | 0.8          | 4
        0.22     | 1        | 5.0       | 'dpm++2mv2' | 6           | true        | 0.9          | 4
    }

    def '/sdcpp/v1/vid_gen (t2v-wo-sample-params)'(@TempDir File videosDir) {
        setup:
        String prompt = """\
        | Inside cargo aircraft. Skydiver standing at open door. Handheld camera. Real footage.
        """.stripMargin().stripIndent()

        String negativePrompt = """\
        | cartoon, anime, CGI, rendered graphics, game engine, low resolution, blurry, distorted body, extra limbs, 
        | duplicate person, floating, unrealistic physics, warped aircraft interior, bad perspective, flickering, 
        | jitter, motion artifacts, overexposed, underexposed, low detail, unrealistic sky, deformed hands, 
        | deformed face, camera clipping through objects, text, watermark, logo, frame corruption
        """.stripMargin().stripIndent()

        when:
        JobExecutionResult executionResult = sdcpp.vidGen(VideoGenerationOptions.builder()
            .prompt(prompt)
            .negativePrompt(negativePrompt)
            .videoFrames(5 * 24)
            .width(512)
            .height(320)
            .fps(24)
            .build())

        and:
        JobStatusResult statusResult = awaitUntilJobStatusResult(executionResult.id)
        File video = new File(videosDir, "skydiver.webm")
        video << statusResult.result.b64Json.decodeBase64()

        then:
        statusResult.id == executionResult.id
        statusResult.completed

        and:
        video.exists()
    }

    def '/sdcpp/v1/vid_gen (t2v-w-sample-params)'(@TempDir File videosDir) {
        setup:
        String loRA = """\
        | <lora:wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise:${loraStrenght}/>
        | <lora:wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise:${loraStrenght}/>
        """.stripIndent().stripMargin().replaceAll('\n', '')

        String prompt = """\
        | ${includeLoRA ? loRA : ''}
        | A luxury supercar slowly arrives at a modern outdoor coffee shop. Several people are sitting at 
        | tables outside. The car comes to a smooth stop. People look toward the vehicle. Photorealistic, 
        | cinematic automotive commercial, realistic daylight, detailed luxury car, realistic crowd, 
        | professional camera movement.
        """.stripIndent().stripMargin()

        String negativePrompt = """\
        | Vibrant colors, overexposed, static, blurry details, subtitles, style, artwork, painting, image, still, 
        | overall grayish, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, 
        | poorly drawn hands, poorly drawn faces, deformed, disfigured, distorted limbs, fingers fused together, 
        | static image, cluttered background, three legs, many people in the background, walking backwards.
        """.stripMargin().stripIndent()

        when:
        String filename = """\
        | car-
        | cfg-${cfgScale}-
        | st-${strength}-
        | flw-${flowShift}-
        | mt-${method}-
        | steps-${sampleSteps}-
        | sec-${seconds}-
        | Q8${includeLoRA ? "-Lora-${loraStrenght}" : ''}.webm
        """.stripMargin().stripIndent().replaceAll('\n', '')

        File video = new File(videosDir, filename)

        and:
        JobExecutionResult executionResult = sdcpp.vidGen(VideoGenerationOptions.builder()
            .prompt(prompt)
            .negativePrompt(negativePrompt)
            .cfgScale(cfgScale)
            .strength(strength)
            .sampleParams(SampleParams.builder()
                .flowShift(flowShift)
                .sampleMethod(method)
                .sampleSteps(sampleSteps)
                .build())
            .videoFrames(seconds * 24)
            .width(832)
            .height(480)
            .fps(24)
            .build())

        and:
        JobStatusResult statusResult = awaitUntilJobStatusResult(executionResult.id)

        and:
        video << statusResult.result.b64Json.decodeBase64()

        then:
        statusResult.id == executionResult.id
        statusResult.completed

        and:
        video.exists()

        where:
        strength | cfgScale | flowShift | method      | sampleSteps | includeLoRA | loraStrenght | seconds
        0.40     | 1.5      | 5.0       | 'dpm++2mv2' | 45          | true        | 1.0          | 1
        0.40     | 1.5      | 5.0       | 'dpm++2mv2' | 45          | false       | 1.0          | 1
    }

    private JobStatusResult awaitUntilJobStatusResult(String jobID) {
        JobStatusResult statusResult = sdcpp.getJob((jobID))
        while (!statusResult.completed) {
            statusResult = sdcpp.getJob(jobID)
            Thread.sleep(1_000)
        }
        return statusResult
    }
}
